version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bvs-ticket-db
    environment:
      POSTGRES_USER: bvsuser
      POSTGRES_PASSWORD: bvspassword
      POSTGRES_DB: ticket_issuer_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
